blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://discord.com/invite/WfMaKPPdeM
    about: Please ask and answer questions in our discord
  - name: Feature Ideas and Requests
    url: https://discord.com/invite/WfMaKPPdeM
    about: Please tell us your ideas on our discord, you can also support us on patreon to directly submit feature requests
