name: Checks

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint


      - name: Unit tests
        run: yarn test:unit


      - name: Build
        run: yarn build


      - name: Build API type artifact
        run: |
          yarn build:api-types
          yarn check:api-types
          tar -czf /tmp/obs-utils-api-types.tgz -C .release/api-types package
