name: Lint
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - uses: pkgxdev/setup@v1
      - name: Lint
        run: |
          yarn
          yarn lint
