name: Playwright Tests
on: 
  push:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn && npx playwright install
    - name: Build with Coverage
      run: yarn instrument
    - name: Start Container
      run: cd ~/docker && docker-compose up -d
    - name: Run Playwright tests
      run: yarn playwright test
      env: 
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        TEST_INSTALL_PASSWORD: ${{ secrets.TEST_INSTALL_PASSWORD }}
        TEST_URL: ${{ secrets.TEST_URL }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Stop Container
      if: always()
      run: cd ~/docker && docker-compose down
