name: "Basic Lint Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@b4401455ef773683d2da2e176e3539cce0fabdc7
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

    - name: Install Requirements
      run: yarn install
    - name: Script Check
      run: yarn lint
    - name: Style Check
      run: yarn stylelint
    - name: Svelte Check
      run: yarn lint:svelte
