name: Release Creation

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@3888ae1b9fbce718b86218b974255090596e99cd
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: AutoModality/action-clean@1077775f5ef0022fc3a9d6f93377921ea3701fa7
    - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

    # get part of the tag after the `v`
    - name: Extract tag version number
      id: get_version
      uses: battila7/get-version-action@d681662789c541f0777208c1f0e82f255f70b28d

    # Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@8c51fbdacd6eeb14b543a993adca02a7c07e6f27
      with:
        files: 'public/module.json'
      env:
        version: ${{steps.get_version.outputs.version-without-v}}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip
    - name: Install
      uses: actions/setup-node@00e1b6691b40cce14b5078cb411dd1ec7dab07f7
      with:
        node-version: 16
      
    - run: yarn install
    - name: build
      run: yarn build

    # Create a zip file with all files required by the module to add to the release
    - run: (cd dist && zip -r ../module.zip *)
    
    - run: zip -ur module.zip LICENSE README.md

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@3ac4132803a6419fa2a7f4e9dbd1d93fceb690b9
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './dist/module.json, ./module.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}
